> forestfires <- read.csv(file.choose())
> opar <- par(no.readonly=TRUE)
> par(mfrow=c(2,2))
> plot(forestfires$temp, forestfires$area, type="b", xlab="Temperature", ylab= "Area")
> plot(forestfires$month, forestfires$area, type="b", xlab="Month", ylab= "Area")
> plot(forestfires$DC, forestfires$area, type="b", xlab="DC", ylab= "Area")
> plot(forestfires$RH, forestfires$area, type="b", xlab="RH", ylab= "Area")
> hist(forestfires$wind)
> hist(forestfires$wind, xlab= "wind(km/hr)", ylab= "Frequency", main = "Histogram of Wind Speed")
> summary(forestfires$wind)
> hist(forestfires$wind, freq= FALSE, xlab= "wind(km/hr)", ylab= "Frequency", Title= "Histogram of Wind Speed")
> lines(density(forestfires$wind))
install.packages("ggplot2")
ggplot(data=forestfires, aes(x=wind,fill=month))+ geom_density(alpha = .3)
pairs(~temp+RH+DC+DMC, data=forestfires)
par(mfrow=c(1,3))
> boxplot(forestfires$wind, xlab = "wind", main= "Boxplot for wind")
> boxplot(forestfires$ISI, xlab = "ISI", main= "Boxplot for ISI")
> boxplot(forestfires$DC, xlab = "DC", main= "Boxplot for DC")

